---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure-container
          image: trupti20/medicure-project
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
  labels:
    app: medicure
spec:
  selector:
    app: medicure
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8082
      targetPort: 8082
